using Moq;

namespace deceptive_enigma;
public class ConfigFixture
{
    public Mock<IConfigProvider> MockConfigProvider {get; }
    public ConfigFixture()
    {
        MockConfigProvider = new();
        var expectedAllowedChars = "0123456789!#%&()*+,-.:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_abcdefghijklmnopqrstuvwxyz{|}~ ".ToList<char>();
        MockConfigProvider.SetupGet(c => c.AllowedChars).Returns(expectedAllowedChars);

        var expectedDictionary = new Dictionary<string, List<string>>
        {
            { "NOUN", new List<string> { "picture", "pickle", "snail", "property", "soda", "books", "lettuce", "hydrant", "pull", "tendency", "toe", "scarf", "rate", "quiver", "reason", "authority", "horn", "plough", "test", "quartz", "ducks", "border", "acoustics", "spoon", "territory", "circle", "division", "achiever", "breath", "jar", "bed", "babies", "pigs", "stomach", "punishment", "pump", "snake", "rhythm", "branch", "stop", "power", "smoke", "camp", "coast", "night", "year", "point", "arithmetic", "loaf", "riddle", "eggnog", "burst", "hat", "hands", "bit", "page", "rice", "key", "ants", "flowers", "lock", "underwear", "nest", "land", "toy", "reaction", "record", "route", "governor", "wheel", "aunt", "channel", "birds", "payment", "science", "toothbrush", "friends", "meeting", "suggestion", "sponge", "sidewalk", "behavior", "current", "increase", "screw", "meal", "harmony", "join", "baby", "watch", "doctor", "move", "adjustment", "sofa", "army", "flame", "pen", "geese", "worm", "gold", "bell", "squirrel", "pail", "church", "magic", "oven", "cattle", "surprise", "cherries", "line", "field", "wire", "hook", "carpenter", "snakes", "head", "sheep", "tongue", "mice", "verse", "bulb", "rain", "destruction", "summer", "train", "hall", "aftermath", "milk", "cherry", "guide", "giraffe", "amusement", "position", "plate", "industry", "ice", "thumb", "kiss", "pig", "ball", "language", "exchange", "plastic", "scale", "lace", "wood", "bird", "eyes", "range", "fold", "pot", "pin", "cow", "brass", "sugar", "trick", "beds", "kettle", "icicle", "can", "story", "wrist", "blow", "cast", "approval", "sense", "bait", "afterthought", "boot", "talk", "seed", "lip", "desire", "argument", "shame", "battle", "comparison", "butter", "mind", "balance", "gun", "tent", "deer", "maid", "oil", "water", "heat", "food", "country", "fly", "basket", "recess", "dress", "cows", "cactus", "guitar", "effect", "partner", "airplane", "soap" } },
            { "VERB", new List<string> { "ending", "washing", "decaying", "whining", "trembling", "hunting", "grabbing", "launching", "treating", "recognising", "fearing", "supporting", "scrapeing", "harassing", "adding", "existing", "announcing", "suiting", "batting", "greasing", "arresting", "searching", "wrecking", "earning", "printing", "replacing", "paddling", "filming", "returning", "wandering", "alerting", "scolding", "curling", "using", "wondering", "squealing", "scaring", "pumping", "sucking", "accepting", "poking", "nailing", "managing", "scorching", "landing", "saving", "depending", "imagining", "collecting", "expanding", "sneezing", "spelling", "preventing", "placing", "judging", "offending", "disagreeing", "attempting", "challenging", "disarming", "regretting", "containing", "tapping", "drumming", "examining", "moaning", "pattng", "crawling", "rhyming", "peeping", "asking", "entertaining", "switching", "tickling", "whistling", "rinsing", "snowing", "allowing", "dragging", "jogging", "confessing", "training", "extending", "interesting", "breathing", "claiming", "slowing", "approving", "scribbling", "unlocking", "balancing", "turning", "tempting", "lying", "joining", "smelling", "colouring", "changing", "noting", "timing", "sailing", "lasting", "fetching", "blinking", "fitting", "deceiving", "sinning", "educating", "flowering", "knitting", "labelling", "racing", "serving", "yawning", "marching", "posting", "reproducing", "explaining", "preaching", "travelling" } },
            { "PREPOSITION", new List<string> { "concerning", "behind", "near", "past", "from", "versus", "anti", "before", "in", "underneath", "into", "towards", "toward", "at", "against", "per", "among", "below", "about", "under", "of", "onto", "outside", "save", "as", "like", "without", "over", "following", "across", "to", "by", "inside", "around", "beneath", "after", "aboard", "since", "with", "above", "via", "regarding", "plus", "beside", "between", "amid", "opposite", "upon", "through", "considering", "minus", "excluding", "up", "excepting", "unlike", "round", "during", "besides", "within", "beyond", "despite", "than", "down", "along", "except", "until"} },
            { "ADVERB", new List<string> {"happily", "gracefully", "yearly", "usually", "dearly", "totally", "bravely", "gently", "well", "even", "terribly", "queerly", "judgementally", "twice", "thoughtfully", "ever", "extremely", "knavishly", "joyously", "angrily", "awkwardly", "already", "selfishly", "officially", "eagerly", "defiantly", "upside-down", "weekly", "broadly", "ultimately", "diligently", "keenly", "vacantly", "dreamily", "furiously", "gratefully", "energetically", "lovingly", "boastfully", "zestily", "fully", "openly", "warmly", "equally", "frequently", "often", "painfully", "strongly", "readily", "knowingly", "simply", "tomorrow", "strictly", "woefully", "fondly", "never", "inquisitively", "limply", "previously", "else", "actually", "intently", "anyway", "daintily", "questioningly", "searchingly", "naturally", "tenderly", "monthly", "normally", "weakly", "too", "briefly", "playfully", "faithfully", "hopelessly", "shakily", "irritably", "foolishly", "closely", "lightly", "youthfully", "nearly", "frenetically", "patiently", "essentially", "dramatically", "upright", "deliberately", "hourly", "fatally", "instantly", "kindly", "eventually", "relatively", "unimpressively", "upliftingly", "less", "sleepily", "obediently", "frankly", "courageously", "miserably", "correctly", "abnormally", "wholly", "wearily", "greatly", "slightly", "quietly", "yesterday", "physically", "probably", "perfectly", "tensely", "rather", "viciously", "uselessly", "interestingly", "literally", "heavily", "owlishly", "only", "accidentally", "swiftly", "bashfully", "joyfully", "unaccountably", "basically", "absentmindedly", "almost", "neatly", "exactly", "deeply", "kissingly", "shrilly", "mainly", "badly", "justly", "yieldingly", "noisily", "forth", "intensely", "optimistically", "loosely", "calmly", "continually", "overconfidently", "unexpectedly", "sedately", "altogether", "cheerfully", "together", "voluntarily", "generally", "thankfully", "quicker", "adventurously", "doubtfully", "safely", "softly", "certainly", "highly", "especially", "recklessly", "occasionally", "jubilantly", "joshingly", "constantly", "questionably", "potentially", "personally", "loyally", "offensively", "positively", "oddly", "wrongly", "solemnly", "mysteriously", "kindheartedly", "gladly", "loudly", "famously", "innocently", "soon", "zealously", "briskly", "vaguely", "carefully", "partially", "jaggedly", "seriously", "unabashedly", "frightfully", "unnaturally", "unethically", "kiddingly", "really", "commonly" } },
        };
        MockConfigProvider.SetupGet(c => c.Dictionary).Returns(expectedDictionary);
        
        var expectedRules = new Dictionary<string, List<string>>
        {
            { "NOUN", new List<string> { "VERB", "ADVERB" } },
            { "VERB", new List<string> { "PREPOSITION", "NOUN" } },
            { "PREPOSITION", new List<string> { "VERB", "NOUN" } },
            { "ADVERB", new List<string> { "VERB", "ADVERB" } },
        };
        MockConfigProvider.SetupGet(c => c.PartsofspeechRules).Returns(expectedRules);

        var expectedConnectors = new List<string> { "NOUN is ADVERB", "ADVERB yet ADVERB" };
        MockConfigProvider.SetupGet(c => c.Connectors).Returns(expectedConnectors);

        var expectedPPOS = new List<string> { "VERB" };
        MockConfigProvider.SetupGet(c => c.PeriodPartsofspeech).Returns(expectedPPOS);
    }
}